# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: myPyllant Library & Home Assistant Component
theme:
  name: material
  icon:
    logo: material/rabbit-variant-outline
  palette:
    scheme: slate
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
  - mkdocstrings
repo_url: https://github.com/signalkraft/mypyllant-component/
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true