name: Github Pages

on:
  push:
    branches:
      - main
      - mkdocstrings

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t mypyllant-docs docs
      - run: docker run -v ~/.ssh:/root/.ssh -v ${PWD}:/build mypyllant-docs gh-deploy --config-file /build/docs/mkdocs.yml --force
